---
abstract: 'Perl wrapper for the Paubox Transactional Email API (https://www.paubox.com/solutions/email-api).'
author:
  - 'Paubox Inc.'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Paubox_Email_SDK
no_index:
  directory:
    - t
    - inc
requires:
  Config::General: '2.63'
  JSON: '4.02'
  REST::Client: '273'
  TryCatch: '1.003002'
version: '1.0'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
